### PR TITLE
Fix typo in package name

### PR DESCRIPTION
**Pull request by karlhorky**
Thanks for this tool, looks interesting! I would enjoy having this as a standalone package apart from `standard`, but that's beside the point of this PR.

This PR is just a quick fix for the typo in the package name.

### CODE REVIEW

**Review by Raynos — APPROVED** [review]

**Comment by Raynos** [comment]
How would this work as a stand-alone package ?

There are eslint rules in a seperate package that you can customize without standard.

**Comment by karlhorky** [comment]
Maybe there is an invalid assumption of mine somewhere, but I would imagine that all of the points from the readme below would be possible without `standard` (or ESLint, for that matter):

> This tsdocstandard is here to help you convert a standard JavaScript project into a JavaScript + jsdoc + typescript project.

> Once you run `tsdocstandard` expect to get 100 warnings about missing jsdoc annotations. That's the point, it will help you convert your JavaScript to typed JavaScript with jsdoc comments.

> Once you fix all the missing annotations expect almost 100% type-coverage ; ( You can measure it with the `type-coverage` library ).

**Comment by Raynos** [comment]
> but I would imagine that all of the points from the readme below would be possible without standard (or ESLint, for that matter)

All of the static analysis for whether the jsdoc annotations are correct relies on eslint for linting the javascript file and it relies on various packages that implement custom eslint rules.

The standard part is indeed optional and you can take the eslint plugins + rules and remove standard

**Comment by karlhorky** [comment]
Cool yeah, if it's built on ESLint then that would be more work to change. Since there's a way to turn off the `standard` rules, seems fine!

**Pull request merged**
